### ISSUE TITLE
ValueFactory attempted to access the Value property of this instance

### ISSUE THREAD

**Issue by SijyKijy** [dansiegel/Prism.Container.Extensions#180]
.NET 5.0 | Prism.Wpf 8.0.0.1909
---
While overriding the `CreateContainerExtension()` method in `App.xaml.cs`, I get the following error
``` ValueFactory attempted to access the Value property of this instance. ```

Code:
```
        protected override IContainerExtension CreateContainerExtension()
        {
            return ContainerLocator.Current;
        }
```

Trace:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=ValueFactory attempted to access the Value property of this instance.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Prism.Ioc.ContainerLocator.get_Current()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)

  This exception was originally thrown at this call stack:
    [External Code]
    Fss.Searcher.App.CreateContainerExtension() in App.xaml.cs
    [External Code]
```

**Comment by lwqwag** [comment]
I met the same issue

**Comment by lwqwag** [comment]
I resolved it by a temporary like the blow code.
`public static class ContainerExtension
    {
        public static IContainerExtension Init(IUnityContainer container)
        {
            var extension = new UnityContainerExtension(container);
            ContainerLocator.SetContainerExtension(() => extension);
            return ContainerLocator.Current;
        }
    }`

**Comment by SijyKijy** [comment]
@lwqwag Doesn't work. `UnityContainerExtension` is abstract class

**Comment by lwqwag** [comment]
> 
> 
> @lwqwag Doesn't work. `UnityContainerExtension` is abstract class
> 
> In general, I work with dry.ioc

I make a little change for dry.ioc

```
 protected override IContainerExtension CreateContainerExtension()
        {
            var extension = ContainerExtension.Init();

            return extension;
        }
        public static class ContainerExtension 
        { 
            public static IContainerExtension Init() 
            { 
                var extension = new DryIocContainerExtension(); 
                ContainerLocator.SetContainerExtension(() => extension); 
                return ContainerLocator.Current; 
            } 
        }
```

**Comment by SijyKijy** [comment]
I can't figure out why, but the `DryIocContainerExtension` doesn't exist. In fact, it's internal
![image](https://user-images.githubusercontent.com/25513191/104166265-92d8fe80-540b-11eb-8258-d44ae138355e.png)

**Comment by nick5454** [comment]
This worked for me:

`public partial class App : Prism.DryIoc.PrismApplication
    {
        protected override IContainerExtension CreateContainerExtension() {
            var extension = new DryIocContainerExtension();
            ContainerLocator.SetContainerExtension(() => extension);
            return ContainerLocator.Current;
        }`

**Comment by dansiegel** [comment]
You should be calling PrismContainerExtension.Init()

**Comment by SijyKijy** [comment]
> You should be calling PrismContainerExtension.Init()

![image](https://user-images.githubusercontent.com/25513191/104572992-733d1280-5665-11eb-87cb-c1ebdef11a6e.png)

Details:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=ValueFactory attempted to access the Value property of this instance.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Prism.Ioc.ContainerLocator.get_Current()
   at Prism.DryIoc.PrismContainerExtension.Init(IContainer container)
   at Prism.DryIoc.PrismContainerExtension.Init(Rules rules)
   at Prism.DryIoc.PrismContainerExtension.Init()

  This exception was originally thrown at this call stack:
    [External Code]
    Fss.Searcher.App.CreateContainerExtension() in App.xaml.cs
```

**Comment by keyhooon** [comment]
this problem must be opened again. because your solution don't make any change, and problem exist

**Comment by keyhooon** [comment]
I found solution for this problem.
You must added this code to your app.xaml.cs .
`        protected override void OnStartup(StartupEventArgs e)
        {
            PrismContainerExtension.Init();
            base.OnStartup(e);
        }`

**Comment by isamBr** [comment]
Please I need your help 
, I got the same issue after me update shiny and prism 
Prism.Container.Extensions" Version="8.0.62"
Prism.Core Version="8.1.97"
Prism.DryIoc.Extensions Version="8.0.62"
"Prism.Forms" Version="8.1.97" 
Prism.Forms.Extended" Version="8.0.62" 
![image](https://user-images.githubusercontent.com/15988391/147388731-ba2e6905-c1d5-49d9-aa6e-65d92f1454de.png)

**Comment by SijyKijy** [comment]
@isamBr 
It helped me to use an older version prism

**Comment by SijyKijy** [comment]
@isamBr
I solved this problem using an old version prism

**Comment by isamBr** [comment]
@SijyKijy Thank you very much for reply back, I tried with downgrade prism to version 7  but the issue still same
 what version are you using ?

**Comment by isamBr** [comment]
@dansiegel 
Can you please assist me with this error caused by  Prism.DryIoc.PrismContainerExtension.Init()
Prism.DryIoc.Extensions version 8.0.62
``` 
System.InvalidOperationException: ValueFactory attempted to access the Value property of this instance.
  at System.Lazy`1[T].ViaFactory (System.Threading.LazyThreadSafetyMode mode) [0x00043] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Lazy.cs:333 
  at System.Lazy`1[T].ExecutionAndPublication (System.LazyHelper executionAndPublication, System.Boolean useDefaultConstructor) [0x00022] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Lazy.cs:351 
  at System.Lazy`1[T].CreateValue () [0x00074] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Lazy.cs:431 
  at System.Lazy`1[T].get_Value () [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Lazy.cs:509 
  at Prism.Ioc.ContainerLocator.get_Current () [0x00000] in /_/src/Prism.Core/Ioc/ContainerLocator.cs:21 
  at Prism.DryIoc.PrismContainerExtension.Init (DryIoc.IContainer container) [0x00005] in /_/src/Prism.DryIoc.Extensions/PrismContainerExtension.cs:21 
  at Prism.DryIoc.PrismContainerExtension.Init (DryIoc.Rules rules) [0x00000] in /_/src/Prism.DryIoc.Extensions/PrismContainerExtension.cs:17 
  at Prism.DryIoc.PrismContainerExtension.Init () [0x00000] in /_/src/Prism.DryIoc.Extensions/PrismContainerExtension.cs:14 
  at SoloProtect.ProjectGoose.App.CreateContainerExtension ()
```
